# 和单行为算法的对比; 和单行为+事件类型的对比
#exp_dan:
#  train:
#    exp: '4302'
#    b_pe: 'da'

#exp_mbstr:
#  train:
#    exp: '4307'
#    b_qkv: True
#    b_ff: True
#    b_head: True
#    b_value: True
#    b_pe: 'pos'
#    n_e_sh: 3
#    n_e_sp: 1
#exp_sasrec_dan_cate_v2:
#  data:
#    mask_prob: 1.2
#    data_type: 'sas'
#  train:
#    exp: '3406'
#    b_pe: 'da'
#    b_cate: True
#    causal: True

exp_dan_cate_v1:
  train:
    exp: '3401'
    b_pe: 'da'
#    b_cate: True

exp_sasrec_dan_cate:
  data:
    mask_prob: 1.2
    data_type: 'sas'
  train:
    exp: '3308'
    b_pe: 'da'
    b_cate: True
    causal: True

# +品类属性：和单行为+属性算法的对比
exp_dan_cate:
  data:
    n_attr: 19
  train:
    exp: '4401'
    b_pe: 'da'

exp_bert4rec_nova_cate:
  data:
    n_attr: 19
  train:
    exp: '4404'
    b_event: 'nova'

exp_bert4rec_dif:
  data:
    n_attr: 19
  train:
    exp: '3303'
    b_event: 'dif_sr'


exp_mbstr_cate:
  data:
    n_attr: 19
  train:
    exp: '4405'
    b_qkv: True
    b_ff: True
    b_head: True
    b_value: True
    b_pe: 'pos'
    n_e_sh: 3
    n_e_sp: 1

#exp_sasrec_cate:
#  data:
#    mask_prob: 1.2
#    data_type: 'sas'
#  train:
#    exp: '4406'
#    b_pe: 'da'
#    causal: True